### Q4. Customer Order Form

In [23]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [24]:
telecall=pd.read_csv('Costomer+OrderForm (1).csv')
telecall

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [25]:
print(telecall['Phillippines'].value_counts(),telecall['Indonesia'].value_counts(),telecall['Malta'].value_counts(),telecall['India'].value_counts())

Error Free    271
Defective      29
Name: Phillippines, dtype: int64 Error Free    267
Defective      33
Name: Indonesia, dtype: int64 Error Free    269
Defective      31
Name: Malta, dtype: int64 Error Free    280
Defective      20
Name: India, dtype: int64


### Ho=The defective % does not varies by center
### Ha=The defective % does  varies by center

In [26]:
defective=np.array([[271,267,269,280,],[29,33,31,20]])
defectivea

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [28]:
chi2,p_val,dof,estimate=stats.chi2_contingency(defective)


In [29]:
print('Chi squared value:',round(chi2,5))
print('p_value:',round(p_val,5))
print('Degree of freedom:',dof)
print('estimate value:\n',estimate)

Chi squared value: 3.85896
p_value: 0.2771
Degree of freedom: 3
estimate value:
 [[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


### Here the p value > α,So we cannot reject the null hypothesis